feat(jsii): allowing twine registry to be set
eladb/projen pull request #140
Opened 2020-10-02 12:30 UTC by JordanSinko

Issue #, if available:
#124 

Description of changes:

This pull request will allow users to release to more than just the default twine repository such as GitHub Packages.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-02 13:30 UTC, eladb requested changes

2020-10-02 13:30 UTC, eladb commented on src/jsii-project.ts
> +  readonly twineRegistryUrl?: string;
Feels like this should be under `python` since it's only relevant when python is configured

2020-10-02 14:22 UTC, JordanSinko commented on src/jsii-project.ts
> +  readonly twineRegistryUrl?: string;
Just the declaration of the type? Or also when setting said variable? Or both?

2020-10-02 16:15 UTC, JordanSinko commented on src/jsii-project.ts
> +  readonly twineRegistryUrl?: string;
I think I understand now. Are you talking about under `JsiiPythonTarget` @eladb ?

2020-10-07 19:47 UTC, eladb commented on src/jsii-project.ts
> +  readonly twineRegistryUrl?: string;
```suggestion

  /**
   * The registry url to use when releasing packages.
   * @default - twine default
   */
  readonly twineRegistryUrl?: string;
```

2020-10-07 19:53 UTC, eladb commented on API.md
> +**twineRegistryUrl**?🔹 | <code>string</code> | The registry url to use when releasing packages.<br/>__*Optional*__
```suggestion
**twineRegistryUrl**?🔹 | <code>string</code> | The registry url to use when releasing packages.<br/>__*Default*__: twine default
```

2020-10-07 19:54 UTC, eladb approved these changes

2020-10-07 20:09 UTC, merged