feat(node): support customizable projen upgrade
eladb/projen pull request #155
Opened 2020-10-05 11:40 UTC by pahud

This PR allows node projects to customize its projen upgrade schedule cron expressions.

Fixes eladb/projen#153

2020-10-05 12:00 UTC, eladb requested changes

2020-10-05 12:00 UTC, eladb commented on src/projen-upgrade.ts
> +          [{ cron: '0 6 * * *' }], // 6am every day
Style:

```suggestion
        schedule: options.autoUpgradeSchedule 
          ? options.autoUpgradeSchedule.map(s => ({ cron: s }))
          : [{ cron: '0 6 * * *' }], // 6am every day
```

2020-10-05 12:00 UTC, eladb commented on src/projen-upgrade.ts
> +   * Customize the projenUpgrade schedule in cron expression.
What's the rationale of supporting a list of CRON schedules instead of a just a single one?

2020-10-07 02:20 UTC, pahud commented on src/projen-upgrade.ts
> +   * Customize the projenUpgrade schedule in cron expression.
The [scheduled events](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events) from GH actions supports multiple schedule entries with cron expression. It allows users to define multiple cron entries like this. I believe most of the time single entry should be enough, but good to support multiple. What do you think?

```
on:
  schedule:
    # “At 06:00 on Sunday.” 
    - cron:  '0 6 * * 0'
    # “At 06:00 on day-of-month 1.”
    - cron:  '0 6 1 * *'
```

2020-10-07 04:43 UTC, eladb commented on src/projen-upgrade.ts
> +   * Customize the projenUpgrade schedule in cron expression.
Okay cool

2020-10-07 04:44 UTC, eladb approved these changes

2020-10-07 04:47 UTC, merged