feat(nextjs): add support for nextjs projects
eladb/projen pull request #167
Opened 2020-10-07 00:32 UTC by Chriscbr

*Issue #, if available:* relates to #158 

*Description of changes:* adds support for NextJS projects

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-07 00:49 UTC, Chriscbr commented
This initial draft uses starter code from [next-learn-starter](https://github.com/vercel/next-learn-starter) under the MIT license, but we can cut it down to just a more minimal file if desired.

I named this `NextJSProject` as opposed to `ReactAppProject` or similar because I have this feeling that NextJS is a lot more batteries-included and opinionated than just a plain React template. I did look into creating a plain React project template, but turns out it's pretty nontrivial just because you need something that will handle all of the bundling and transpilation (i.e. babel and webpack), and those require several more config files. I imagine those are features users might eventually want options for, but this solution is at least an easier first step.

Some next steps are to add more properties / customizations (perhaps per the template referenced in #158) and also to add support for TypeScript versions of NextJS projects. Some suggested ways to go about this:

1. create a class `TypeScriptNextJSProject` that extends `TypeScriptAppProject`
2. create a class `NextJSTypeScriptProject` that extends `NextJSProject`
3. add a `typescript?` option as a parameter to `NextJSProject`

@eladb Does projen support multiple inheritance in any fashion, or is jsii a restrict us in that regard? It's a question that's been on my mind for a while, to be honest. I'm just wondering because JS projects do mix and match different libraries and frameworks etc., so I'm wondering what the best way to go about representing, for example, the 2x2 possible choices for (React, not-React) x (TypeScript, not-TypeScript) projects, as one example.

2020-10-07 04:59 UTC, eladb requested changes
Great job looks awesome. A few minor comments

2020-10-07 04:59 UTC, eladb commented on src/next.ts
> +export interface NextJSProjectOptions extends NodeProjectOptions {
Rename to `NextJs` (jsii prefers no all caps abbreviations)

2020-10-07 04:59 UTC, eladb commented on src/next.ts
> +  public readonly pagesdir: string;
```suggestion
  public readonly pagesDir: string;
```

2020-10-07 04:59 UTC, eladb commented on src/next.ts
> +  public readonly assetsdir: string;
```suggestion
  public readonly assetsDir: string;
```

2020-10-07 05:02 UTC, eladb commented
> does projen support multiple inheritance in any fashion, or is jsii a restrict us in that regard? 

The way to implement this is through `Component` classes that can be composed together into a project.

2020-10-13 11:33 UTC, eladb approved these changes

2020-10-13 11:37 UTC, merged