WIP: adding doc for cdk construct
eladb/projen pull request #179
Opened 2020-10-12 02:06 UTC by mbonig

*Issue #, if available:*

*Description of changes:*

Added first draft doc for using the AWS CDK construct library. Notes requested.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-12 06:30 UTC, eladb requested changes
Initial round of feedback

2020-10-12 06:30 UTC, eladb commented on docs/awscdk-construct.md
> +# Getting Started
why not use `projen new`?

2020-10-12 06:30 UTC, eladb commented on docs/awscdk-construct.md
> +  authorAddress: "",
Instead of needing to maintain this, I rather we implement #168 and instruct people to use `npx projen new`

2020-10-12 06:30 UTC, eladb commented on docs/awscdk-construct.md
> +  entrypoint: 'lib/index.js',
How is `entrypoint` related to CDK dependencies? (also, I don't think it needs to be set up)

2020-10-12 06:30 UTC, eladb commented on docs/awscdk-construct.md
> +With the above example you'll get a package.json that looks like this:
I don't think it's very useful to show the synthesized output for everything. Just describe the behavior. In this case, I would write something like:

`cdkDependencies` will add both `dependencies` and `peerDependencies` to your `package.json` file with a **caret** semver requirement. You can set `cdkVersionPinning` to `true` to use a fixed version, but this means that any consumer of your library will have to use this exact CDK version.

2020-10-12 06:30 UTC, eladb commented on docs/awscdk-construct.md
> +### JSII Packaging
This is not just packaging, it's also publishing.

2020-10-12 06:30 UTC, eladb commented on docs/awscdk-construct.md
> +Will render out the following to the package.json:
Again, redundant. It also modifies the GitHub workflows.

2020-10-12 06:30 UTC, eladb commented on docs/awscdk-construct.md
> +
In order to the github workflows to work, users need to add github secrets. This should be documented.

2020-10-12 06:30 UTC, eladb commented on docs/awscdk-construct.md
> +# AWS CDK - Construct library
```suggestion
# AWS CDK Construct Library
```

2020-10-12 06:30 UTC, eladb commented on docs/awscdk-construct.md
> +This projen type is used for building AWS CDK constructs using the JSII.
Explain what's the value of using jsii and include some references to jsii docs.

jsii is spelled all lowercase BTW

2020-10-12 13:40 UTC, mbonig commented on docs/awscdk-construct.md
> +# Getting Started
Yes, I'll add steps to use projen new instead of expecting this more manual approach.

2020-10-12 13:41 UTC, mbonig commented on docs/awscdk-construct.md
> +  authorAddress: "",
👍

2020-10-12 13:42 UTC, mbonig commented on docs/awscdk-construct.md
> +  entrypoint: 'lib/index.js',
Totally forgot mentioning this. Since most people probably didn't name their construct's file 'main.ts' I figured this would need to be overridden. I'll make that clearer.

2020-10-12 13:43 UTC, mbonig commented on docs/awscdk-construct.md
> +With the above example you'll get a package.json that looks like this:
Will do. I was putting the output because that usually helps me understand how properties transfer but I can remove it.

2020-10-12 13:43 UTC, mbonig commented on docs/awscdk-construct.md
> +### JSII Packaging
But only if the related workflows are setup, right?

2020-10-12 14:33 UTC, eladb commented on docs/awscdk-construct.md
> +### JSII Packaging
No, workflows are automatically created as soon as you specify `python`, `java` etc. No additional setup is required (besides installing the secrets to your github repo).

2020-10-13 03:34 UTC, mbonig commented
I addressed all issues. I also added some additional coverage I didn't notice the first time around.

2020-10-18 11:56 UTC, eladb requested changes
Missing:

- Enabling API compatibility checks
- Release management
- Project structure (src, lib, test, resources,...)
- Workflow (what is the meaning of each command).

Some of those should be part of the node/typescript/jsii project docs, but since we don't have them lets try to cover all of it here and then we can move stuff around.

Would be nice to start structuring our docs according to project types and then we can just cross reference.

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +A `README.md` file is not created but encouraged. It is required for publishing your construct for Python (see [jsii publishing](#jsii-publishing)).
Should we bootstrap one?

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +  entrypoint: 'lib/our-s3-bucket.js',
Not sure what's up here? The practice that I'd recommend is leaving this as the default `lib/index.js` and adding this to `index.ts`:

```ts
export * from './our-s3-bucket';
```

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +rename your file to `index.js` and leave this un-set.
Remove

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +
Explain why both deps and peer deps are required (this is actually resolved by npm@7)

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +As this is a [jsii](https://github.com/aws/jsii) constructs, it will cross-compile to other languages.  You can set up
```suggestion
As this is a [jsii](https://github.com/aws/jsii) project, it will cross-compile to other languages.  You can set up 
```

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +* .net - NUGET_API_KEY
```suggestion
* .NET - NUGET_API_KEY
```

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +to be setup:
Add a reference to [jsii-release](https://github.com/aws/jsii-release) which has detailed instructions on how to obtain these secrets.

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +### Standard Node Module Fields
Why H3 instead of H2?

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +
Add TOC

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> + `props.defaultReleaseBranch`) the construct is built, anti-tampered, version bumped with a commit, pushed back to git,
Replace the term "construct" across the doc with "construct library" or just "library"

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +Additionally, a [dependabot](https://dependabot.com/) file will be added unless `dependabot` is set to 'false'.
This should be under "Dependencies", not "Workflows".

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +### CDK Dependencies
```suggestion
### Dependencies
```

Please also add a section about non-CDK dependencies. Specifically, the difference between jsii deps and non-jsii deps (which require bundling)

2020-10-18 11:56 UTC, eladb commented on docs/awscdk-construct.md
> +### docgen
```suggestion
### API Documentation
```

2020-10-18 19:15 UTC, mbonig commented on docs/awscdk-construct.md
> +A `README.md` file is not created but encouraged. It is required for publishing your construct for Python (see [jsii publishing](#jsii-publishing)).
I added a Readme class.

2020-10-18 19:16 UTC, mbonig commented on docs/awscdk-construct.md
> +  entrypoint: 'lib/our-s3-bucket.js',
👍

2020-10-18 19:19 UTC, mbonig commented on docs/awscdk-construct.md
> +rename your file to `index.js` and leave this un-set.
👍

2020-10-18 19:29 UTC, mbonig commented on docs/awscdk-construct.md
> +
I assume changes are needed if projen is to support the new npm@7 algorithm and not add the cdk deps to `dependencies`?

2020-10-18 19:30 UTC, mbonig commented on docs/awscdk-construct.md
> +As this is a [jsii](https://github.com/aws/jsii) constructs, it will cross-compile to other languages.  You can set up
👍

2020-10-18 19:30 UTC, mbonig commented on docs/awscdk-construct.md
> +* .net - NUGET_API_KEY
👍

2020-10-18 19:31 UTC, mbonig commented on docs/awscdk-construct.md
> +to be setup:
👍

2020-10-18 19:32 UTC, mbonig commented on docs/awscdk-construct.md
> +### Standard Node Module Fields
missed some cleanup... fixed now.

2020-10-18 19:44 UTC, mbonig commented on docs/awscdk-construct.md
> + `props.defaultReleaseBranch`) the construct is built, anti-tampered, version bumped with a commit, pushed back to git,
I think I got the right ones. Some places still seemed 'construct' was best.

2020-10-18 20:07 UTC, mbonig commented on docs/awscdk-construct.md
> +### docgen
👍

2020-10-18 21:38 UTC, mbonig commented
> Missing:
> 
> * Enabling API compatibility checks

not sure what you're looking for here. More details about this? https://github.com/aws/jsii/tree/master/packages/jsii-diff

> * Release management

Added the Workflow section which should cover this, but let me know if there were other details you are thinking of.

> * Project structure (src, lib, test, resources,...)

Added. I didn't cover all the individual files, but added a comment about the resources directory.

> * Workflow (what is the meaning of each command).
> 

Added as `Scripts`

> Some of those should be part of the node/typescript/jsii project docs, but since we don't have them lets try to cover all of it here and then we can move stuff around.
> 
> Would be nice to start structuring our docs according to project types and then we can just cross reference.

I figured one thing that'll be useful is a breadcrumb at the top showing the hierarchy. Right now it doesn't link to any other docs but it should in the future (when more docs like this are built).

2020-10-19 18:46 UTC, eladb commented on docs/awscdk-construct.md
> +## Standard Node Module Fields
```suggestion
## Module Metadata
```

2020-10-19 18:46 UTC, eladb commented on docs/awscdk-construct.md
> +  authorAddress: "benisrae@amazon.com",
Please normalize all quotes to single quotes (I know that `projen new` generates with double...)

2020-10-19 18:46 UTC, eladb commented on docs/awscdk-construct.md
> +see [this issue](https://github.com/aws/aws-cdk/issues/5064). You can set cdkVersionPinning to true to use a fixed
```suggestion
see [this issue](https://github.com/aws/aws-cdk/issues/5064). You can set `cdkVersionPinning` to `true` to use a fixed 
```

2020-10-19 18:46 UTC, eladb commented on docs/awscdk-construct.md
> +
Yes, but it will take a while for users to migrate and this is a construct _library_, so we can't rely on people using npm@7.

Also, in CDK2.0, you'll only need a peer dependency.

2020-10-19 18:46 UTC, eladb commented on docs/awscdk-construct.md
> +As this is a [jsii](https://github.com/aws/jsii) project, it will cross-compile to other languages.  You can set up
```suggestion
As this is a [jsii project](./jsii.md), it will cross-compile to other languages.  You can set up 
```

2020-10-19 19:08 UTC, mbonig commented on docs/awscdk-construct.md
> +
k. I don't believe there is anything to add to this until we decide npm@7 is adopted enough.

2020-10-19 19:36 UTC, mbonig commented
Anything else I missed?

2020-10-20 13:01 UTC, eladb approved these changes

2020-10-20 13:05 UTC, merged