feat(nextjs): add support for typescript nextjs projects
eladb/projen pull request #197
Opened 2020-10-14 06:14 UTC by Chriscbr

*Issue #, if available:* N/A

*Description of changes:* Added a nextjs-ts project option which extends the typescript-app project class. Grouped some options together between the two nextjs project types, and implemented basic Next.js tsconfig project defaults so that both nextjs and nextjs-ts project types work out of the box.

----

Some notes:

I made a slight modification of TypeScriptConfig so that I can mark `tsconfig.json` as mutable, since the 'next build' command fails if it's immutable. The reason for this I believe is that the 'next' command tries to automatically change your tsconfig file if it sees that some options set incorrectly based on what Next.js's build system wants. I could send a feature request to the Next.js team to see if they can enable a CLI flag that skips this behavior, but for now this workaround makes the most sense.

There is a two-line file named `next-env.d.ts` that must be added to the root directory for TypeScript Next.js projects to successfully build. I included this in the PR, but it's worth suggesting that we should also eventually add an escape hatch so a user can omit or change the `next-env.d.ts` file if needed -- but I'm not sure what that mechanism should be, so I've left that unimplemented for now.

Lastly, many Next.js projects don't have test directories from what I've seen, so I didn't include sample code for any. But this causes eslint to complain, and changing how the default eslint command behaves warrants a separate PR (see #182), and using `eslint: false` can lead to #180, so I ended up adding a small piece of cruft in the project constructor for now:

```
this.addTestCommand('echo 0');
```

----

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-14 06:27 UTC, Chriscbr commented
Not totally sure why this build is failing (works fine locally) -- is it not possible to override the docstring of class?

2020-10-14 11:24 UTC, eladb requested changes
minor-

2020-10-14 11:24 UTC, eladb commented on src/typescript.ts
> +  public file: JsonFile;
```suggestion
  public readonly file: JsonFile;
```

2020-10-14 11:24 UTC, eladb commented on src/typescript.ts
> +  readonly moduleResolution?: string;
enum?

2020-10-14 11:24 UTC, eladb commented on src/typescript.ts
> +  readonly jsx?: string;
enum?

2020-10-14 11:24 UTC, eladb commented on src/typescript.ts
> +   */
@default

2020-10-14 11:24 UTC, eladb commented on src/next.ts
> +    this.srcDir = options.srcdir ?? 'pages';
Kind of don't like the inconsistency `srcDir` versus `srcdir`. Let's normalize to `srcdir`?

2020-10-14 11:24 UTC, eladb commented on src/next.ts
>      });
You could reuse this with the `NextProject` using `Component`s. You can create a `NextComponent` and then compose it here and there.

2020-10-23 06:08 UTC, eladb approved these changes
🤗🤗🤗

2020-10-23 17:35 UTC, merged