Feat/external project discovery
eladb/projen pull request #212
Opened 2020-10-20 22:28 UTC by kcwinner

*Issue #, if available:* [193](https://github.com/eladb/projen/issues/193)

*Description of changes:*
* Alters the command syntax slightly to make `PROJECT-TYPE` an optional positional parameter
* Adds two new options for creating a new project from a remote module: `--from` and `--name`
* Adds a `discoverRemote` method to inventory to accommodate external jsii type lookups  
* Adds readme info on adding projects from external modules
* Fixes a few potential null/undefined errors in node-project

*Testing:*
Tested with [cdk-appsync-project](https://github.com/kcwinner/cdk-appsync-project). Works using local installs and via npm packages.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-21 05:45 UTC, eladb requested changes
This is an awesome contribution! Thanks so much for picking this up!

See my comment about the mixup with `--name`. I feel it's my fault for using that as an example in the RFC...

2020-10-21 05:45 UTC, eladb commented on README.md
> +projen is bundled with many project types out of the box, but it can also work with project types and components defined in external jsii modules (the reason we need jsii is because projen uses the j
Wrap to 100 chars

2020-10-21 05:45 UTC, eladb commented on README.md
> +Say we have a module in npm called projen-vue which includes a single project type for vue.js:
```suggestion
Say we have a module in npm called `projen-vue` which includes a single project type for vue.js:
```

2020-10-21 05:45 UTC, eladb commented on README.md
> +$ npx projen new --from projen-vue vuejs-ts@^2 --name my-vuejs-sample
I think there's a mix up here:

`from` is supposed to be a package spec passed to `npm i` (or `yarn add`) and therefore can optionally include a version spec. The first positional is the project type (e.g `vuejs-ts`) and `--name` is just an optional property of the project type that can be passed to assign a value to this property (like all other props).

```suggestion
$ npx projen new --from projen-vue@^2 vuejs-ts --name my-vuejs-sample
```

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +    args.positional('PROJECT-TYPE', { describe: 'Required if --from is not specified', type: 'string' });
```suggestion
    args.positional('PROJECT-TYPE', { describe: 'optional only when --from is used and there is a single project type in the external module', type: 'string' });
```

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +    args.option('name', { type: 'string', alias: 'n', desc: 'Name of project type if module contains more than one project type' });
Remove this. See my explanation above 

```suggestion
```

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +    args.option('from', { type: 'string', alias: 'f', desc: 'External jsii npm module to create project from' });
```suggestion
    args.option('from', { type: 'string', alias: 'f', desc: 'External jsii npm module to create project from. Supports any package spec supported by yarn (such as "my-pack@^2.0")' });
```

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +    args.positional('PROJECT-TYPE', { describe: 'Required if --from is not specified', type: 'string' });
add an `.example()` for using `--from`

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> -    for (const pjid of inventory.discover().map(x => x.pjid)) {
We've lost this friendly message. Right?

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +  // fail if .projenrc.js already exists
Why again?

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +    if (args.from && args.from !== '') {
In javascript, an empty string is falsy:

```suggestion
    if (args.from) {
```

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +    logging.error('No projects found in remote module');
```suggestion
    logging.error(`No projects found in remote module ${moduleName}`);
```

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +    process.exit(1);
Throw an error instead of exiting here

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +      logging.error('Multiple projects found in package. Please specify a project name with --name option');
1. Throw instead of .error()
2. Include the list of project types in the error.

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +    const projectName = args.name;
This should be the first positional argument which is project _type_ (such as `typesscript-app`), not the project name such as `my-awesome-app` (name is a just a prop of the project type).

See "mixup" above.

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +    type = projects.find(project => project.typename === '');
```suggestion
    type = projects.find(project => project.typename === projectType);
```

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +  for (const [key, value] of Object.entries(args)) {
Please  extract this code from the normal code path and reuse here. Doesn't make sense to duplicate this mess :-)

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +  const moduleName = module.split('/').slice(-1)[0].trim().split('@')[0].trim(); // Example: ./cdk-project/dist/js/cdk-project@1.0.0.jsii.tgz
DRY (don't repeat yourself)

2020-10-21 05:45 UTC, eladb commented on src/cli/cmds/new.ts
> +  }
Extract to a function and explain what's done here

2020-10-21 05:45 UTC, eladb commented on src/inventory.ts
> +export interface JsiiType {
Doesn't make sense to export this

2020-10-21 05:45 UTC, eladb commented on src/node-project.ts
>      const readDeps = (user: Record<string, string>, current: Record<string, string>) => {
What's the use case of `current` being undefined?

At any rate, fix the type info:

```suggestion
    const readDeps = (user: Record<string, string>, current?: Record<string, string>) => {
```

2020-10-21 05:45 UTC, eladb commented on yarn.lock
> -"@typescript-eslint/scope-manager@4.4.1":
Revert yarn lock change

2020-10-21 05:45 UTC, eladb commented on src/inventory.ts
> +export function discoverRemote(externalJsii: { [name: string]: JsiiType }) {
Not sure I understand why this is needed? Can't we just reuse the same code that we have for the built-in discovery?

2020-10-21 05:48 UTC, eladb commented
okay, fixed the [rfc](https://github.com/eladb/projen/issues/193#issuecomment-712600369) to use a different prop other than `--name` and move the version spec from the project type to the module name. Sorry about that.

2020-10-21 11:56 UTC, kcwinner commented on src/inventory.ts
> +export interface JsiiType {
This is used in `new.ts` under the handleFromNPM
`const externalJsiiTypes: { [name: string]: inventory.JsiiType } = fs.readJsonSync(path.join(packageDir, '.jsii')).types;`

2020-10-21 13:36 UTC, kcwinner commented on src/node-project.ts
>      const readDeps = (user: Record<string, string>, current: Record<string, string>) => {
Made the change. Also, was never able to track down what is causing the issue but it's only on external projects as far as I can tell. I first noticed it before working on this and just trying to get projen to work with external packages in a different manner.

<img width="344" alt="Screen Shot 2020-10-21 at 9 31 54 AM" src="https://user-images.githubusercontent.com/2728868/96726913-7c795480-1380-11eb-8e37-567a9319eacb.png">

2020-10-21 13:55 UTC, kcwinner commented on src/cli/cmds/new.ts
> -    for (const pjid of inventory.discover().map(x => x.pjid)) {
Added this back in with a fallback to the `yargs.showHelp();` since we can get there by specifying nothing but there is no check on the (now) optional positional parameter of PROJECT-TYPE

2020-10-21 14:12 UTC, kcwinner commented on src/cli/cmds/new.ts
> +  // fail if .projenrc.js already exists
All the local projects are handled in the builder for each command. Since we can't ( grab the package at build time we need to make sure to check before running, which is why I extracted it to a method.

It may make sense to have at the top of the handler here as well, though

2020-10-21 14:31 UTC, kcwinner commented on src/cli/cmds/new.ts
> +  for (const [key, value] of Object.entries(args)) {
Extracted to `buildProjenConfigParams`

2020-10-21 14:38 UTC, kcwinner commented on src/cli/cmds/new.ts
> +  // fail if .projenrc.js already exists
I'll do whatever makes sense. Moved to the tope of the handler for now.

2020-10-21 17:33 UTC, kcwinner commented on src/cli/cmds/new.ts
> +    process.exit(1);
These messages look kind of cluttered since the help is output on a failure as well

<img width="717" alt="Screen Shot 2020-10-21 at 1 32 49 PM" src="https://user-images.githubusercontent.com/2728868/96756325-eb1ada00-13a1-11eb-99eb-20f9c3a359e3.png">

2020-10-21 19:49 UTC, eladb commented on src/cli/cmds/new.ts
> +    process.exit(1);
We should catch these exceptions at the program level and print only the message in nice bold red font.

2020-10-22 11:59 UTC, eladb requested changes
Submitted a PR against your branch with some changes (https://github.com/kcwinner/projen/pull/1)

2020-10-22 12:31 UTC, kcwinner commented
> Submitted a PR against your branch with some changes ([kcwinner#1](https://github.com/kcwinner/projen/pull/1))

2020-10-22 12:32 UTC, kcwinner commented
> > Submitted a PR against your branch with some changes ([kcwinner#1](https://github.com/kcwinner/projen/pull/1))

Merged and will fix here

2020-10-22 12:52 UTC, kcwinner commented on src/cli/cmds/new.ts
> +    const tmpdir = fs.mkdtempSync(path.join(os.tmpdir(), 'projen-'));
Should this get cleaned up? I used `node_modules.local` since it's relative to the project. Otherwise, the project gets stuff into something like `/var/folders/8k/2_wzn5qs4qz_qcw0ls5pv_ph0000gn/T/projen-iurcCi/pkg.tgz` and just sits on the machine. 

I'm not sure how common the local file use case is. It's obviously the best way for me to do most of the testing since it can iterate without publishing to NPM

2020-10-22 12:54 UTC, kcwinner commented on src/cli/cmds/new.ts
> +    devDeps: [spec],
This doesn't work for local packages. Working on a fix. Can either use the `PackageInfo` interface as before or a specific check right before this

2020-10-22 13:14 UTC, kcwinner commented on src/inventory.ts
> +export interface JsiiType {
This has been reverted. No longer needed with your changes to discovery

2020-10-22 13:28 UTC, kcwinner commented
Other than not loving the temp package folder, everything else works after the merge with the slight dependency info change (as noted in the conversation inline).

I have not yet tested this with remote git urls (e.g. `git@github.com/awesome/projen-vuejs#1.2.3`). My main reason is that by default `.jsii` files are ignored (although this isn't specified by jsii anywhere). What is the likelihood of this scenario and support for it? I'm assuming it will need special consideration just as local packages do.

2020-10-23 05:40 UTC, eladb commented on src/cli/cmds/new.ts
> +    const tmpdir = fs.mkdtempSync(path.join(os.tmpdir(), 'projen-'));
I think it's fine not to clean it up from /tmp

2020-10-23 05:42 UTC, eladb approved these changes

2020-10-23 05:42 UTC, eladb commented on src/cli/cmds/new.ts
> +    const moduleName = spec.split('/').slice(-1)[0].trim().split('@')[0].trim(); // Example: ./cdk-project/dist/js/cdk-project@1.0.0.jsii.tgz
What happens if the name of the file doesn't match this format? Any tarball can be used from yarn's perspective. 

The only way to really know the name is to unpack the file and read it's package json.

I guess we can unpack it to /tmp and then point yarn to this directory.

Wdty?

2020-10-23 05:47 UTC, merged