feat: add support for docker-compose.yml
eladb/projen pull request #230
Opened 2020-10-26 02:17 UTC by misterjoshua

2020-10-26 06:11 UTC, eladb requested changes
Great job! Looks awesome. A few minor comments.

2020-10-26 06:11 UTC, eladb commented on src/docker-compose.test.ts
> +      dependsOn: ['db'],
Would have been cool if this was strongly coupled through a reference:

```ts
const db = dc.addService(...);
const wp = dc.addService('wordpress', {
  dependsOn: [db]
  ...
});

// or through an imperative api
wp.addDependsOn(db);
```

2020-10-26 06:11 UTC, eladb commented on src/docker-compose.ts
> +   * @default no name is added
Conventionally, if the default is not a specific value, we use "-" for the value:

```ts
@default - no name is added
```

2020-10-26 06:11 UTC, eladb commented on src/docker-compose.ts
> +    protocol: DockerComposeProtocol = DockerComposeProtocol.TCP,
I'd move `protocol` into an options struct so it's extensible in the future. 

As a rule of thumb, no more than 2 positional arguments.

2020-10-26 06:11 UTC, eladb commented on src/docker-compose.ts
> +  addService(name: string, description: DockerComposeServiceDescription): void {
Specify access modifier:

```suggestion
  public addService(name: string, description: DockerComposeServiceDescription): void {
```

2020-10-27 00:21 UTC, misterjoshua commented
Good ideas! I'll get to these changes tonight or tomorrow night. :)

2020-10-27 03:39 UTC, misterjoshua commented
@eladb I think I've got your review items handled. In addition to your comments, I fleshed out the imperative interfaces in general, fixed a few bugs, and added more tests.

2020-10-27 07:21 UTC, eladb approved these changes

2020-10-27 07:24 UTC, merged